version: "3.9"
services:
  fast-api:
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./app:/src/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
